### ISSUE TITLE
10.md中函数指针那块后面sizeof()的表达问题

### ISSUE THREAD

**Issue by xiaofan8421** [wrestle/gitbook#5]
sizeof()算是C语言的一个关键字把，肯定不能当做函数，是在编译时就确定大小了，而不是运行时

**Comment by wrestle** [comment]
OK, 感谢指正

**Comment by wrestle** [comment]
> sizeof()算是C语言的一个关键字把，肯定不能当做函数，是在编译时就确定大小了，而不是运行时
OK, 感谢指正

**Comment by wrestle** [comment]
> sizeof()算是C语言的一个关键字把，肯定不能当做函数，是在编译时就确定大小了，而不是运行时

感谢指正

**Comment by wrestle** [comment]
FIX
